# Generated by Django 4.1.7 on 2023-02-19 13:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_comments_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 13, 6, 50, 592103, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
