# Generated by Django 4.1.7 on 2023-02-20 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_news_slug_alter_comments_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published_date',), 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 20, 33, 786059, tzinfo=datetime.timezone.utc)),
        ),
    ]
