# Generated by Django 4.1.7 on 2023-02-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_comments_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 15, 6, 40, 869589, tzinfo=datetime.timezone.utc)),
        ),
    ]
