# Generated by Django 4.1.7 on 2023-02-20 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_post_body_alter_comments_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 24, 29, 493938, tzinfo=datetime.timezone.utc)),
        ),
    ]
