# Generated by Django 4.1.7 on 2023-02-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published_date',)},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='published',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.AddField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 12, 29, 33, 703989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 12, 29, 33, 703989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
