# Generated by Django 4.1.7 on 2023-02-19 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_news_status_alter_comments_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique_for_date='published_date'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 13, 15, 2, 252076, tzinfo=datetime.timezone.utc)),
        ),
    ]
