# Generated by Django 4.1.7 on 2023-02-20 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_news_options_alter_comments_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 14, 31, 2, 443658, tzinfo=datetime.timezone.utc)),
        ),
    ]
